const PAGINATION_OFFSET_DEFAULT = 0;
const PAGINATION_LIMIT_DEFAULT = 20;
const PAGINATION_MAX_LIMIT = 100;
const PAGINATION_MIN_LIMIT = 1;
const PAGINATION_MIN_OFFSET = 0;

export {
  PAGINATION_OFFSET_DEFAULT,
  PAGINATION_LIMIT_DEFAULT,
  PAGINATION_MAX_LIMIT,
  PAGINATION_MIN_LIMIT,
  PAGINATION_MIN_OFFSET,
};
