variables:
  awsServiceConnection: building-blocks-shared-ecr
  awsRegion: eu-west-1
  ecrEndpoint: 428528001781.dkr.ecr.eu-west-1.amazonaws.com
  environment: LifeEvents-dev
  services: profile

  nextPublicProfileServiceEntryPoint: https://profile.dev.blocks.gov.ie
